# Generated by Django 5.1.1 on 2024-09-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='CustomUser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='CustomUser_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='swipeaction',
            name='action',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('super like', 'SuperLike')], max_length=10),
        ),
    ]
